enableImmutableInstalls: false

enableStrictSsl: false

# httpProxy: 'http://127.0.0.1:7890' # 代理选择添加

# httpsProxy: 'http://127.0.0.1:7890' # 代理选择添加

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
